server/controllers/image.controller.js, server/routes/image.route.js
=> [API] Sửa image API

client/package-lock.json, client/package.json
=> [Lib] Add axios

client/src/api/index.js, client/src/api/user.js
=> [API] add api function

server/data/users.js
Nhàn simper
Thêm role vào user data
API
=> [API] add role users

client/tailwind.config.js
Nhàn simpper
Sửa file config của tailwind
Repo
=> [Repo] change tailwind config

client/package-lock.json, client/package.json
Tri Pu
Đổi phiên bản của axios xuống 0.27.0
Repo
=> [Repo] Change axios version

client/src/assets/tailwind.css, client/tailwind.config.js
TriPu
Thêm config của tailwind
Repo
=> [Repo ] Change tailwind config

client/src/components/Loading.jsx
TriPu
Thêm thành phần Loading 
Repo
=> [Repo] Add loading component

client/src/layouts/defaults.jsx, client/src/pages/NoPage.jsx
Nhàn simp lỏd
Thêm giao diện trang no page
Page
=> [Page] add page no-page

client/src/components/Footer.jsx
=> [Footer] Modify footer

client/src/assets/tailwind.css, client/src/components/Header.jsx, client/tailwind.config.js
Tri
Thêm các thẻ Link và xóa css một vài chỗ
=> [Header] Modify header

server/data/products.js, server/data/users.js
=> [Config] Remove dotenv

client/src/components/ProductCard.jsx, client/src/utils/index.js, client/tailwind.config.js
Nhàn simp lỏd
Thêm product card
Page
=> [Page] add product card

client/src/api/cart.js, client/src/api/product.js
TriPu
Thêm API cập nhật giỏ hàng
API
=> [API] Add cart update cart

client/src/components/Footer.jsx
Nhàn simp lỏd
Sửa import icon footer
Page
=> [Page] fix import footer

client/src/api/product.js
Nhàn simp lỏd
Thêm hàm lấy tất cả sản phẩm
API
=> [API] add get all product

client/src/components/Auth.jsx
Tripu
Add logout feature in AuthContext
API
=> [API] add logout

client/src/pages/Payment.jsx
Đinh Thị Ánh Nguyệt
Thêm thanh toán 
Payments
=> [Payment] Add payment page

client/src/components/Footer.jsx
Nhán
Thêm đường kẻ phân chia body là footer
Footer
=> [Footer] add line dividing body and footer

client/src/components/PrivateRoute.jsx
TriPu
Xem tên PR đi <(")
Router
=> [Router] Add popup for private router

server/routes/index.route.js
=> [API] <(")

client/tailwind.config.js
Nhán
Chuyển tailwind thành desktop first
Repo
=> [Repo] change to desktop first

client/src/assets/tailwind.css, client/src/components/Footer.jsx, client/src/components/Header.jsx, client/src/layouts/defaults.jsx, client/src/pages/Home.jsx, client/src/pages/Login.jsx, client/src/pages/Products.jsx, client/src/pages/Profile.jsx, client/src/pages/SignUp.jsx, client/src/utils/index.js, client/tailwind.config.js
TriPu
Thêm responsive thôi hỏi làm gì <(")
Chưa làm Payment, ProductInfo
=> [Header][Footer][Sign in][Sign out][Home][Profile][Products] Responsive

client/src/index.js, client/src/layouts/NoFooter.jsx, client/src/pages/NoPage.jsx
TriPu
Thêm responsive cho nopage
NoPage
=> [NoPage] Responsive

client/.prettierrc, client/README.md, client/package-lock.json, client/package.json, client/prettier.config.js, client/src/api/init.js, client/src/api/product.js, client/src/assets/tailwind.css, client/src/components/Footer.jsx, client/src/components/Header.jsx, client/src/components/Loading.jsx, client/src/components/PrivateRoute.jsx, client/src/components/ProductCard.jsx, client/src/components/ProductInfo.jsx, client/src/layouts/NoFooter.jsx, client/src/layouts/defaults.jsx, client/src/pages/AboutUs.jsx, client/src/pages/Home.jsx, client/src/pages/Login.jsx, client/src/pages/NoPage.jsx, client/src/pages/ProductInfo.jsx, client/src/pages/Products.jsx, client/src/pages/Profile.jsx, client/src/pages/SignUp.jsx, client/src/utils/index.js, client/tailwind.config.js
=> [Repo] Format tailwind and add productInfo responsive

client/src/api/order.js, client/src/pages/Payment.jsx, client/src/pages/ProductInfo.jsx, server/data/users.js
NHANes
Thêm màn tính tiền （ᗜ ‸ ᗜ）
Page
=> [Page] add payment page

client/src/components/ProductInfo.jsx, client/src/pages/Profile.jsx
NHANes
Sửa giao diện trang hồ sơ
Page
=> [Page] fix profile page

client/src/api/ordered.js, client/src/api/user.js, client/src/pages/Payment.jsx, client/src/pages/Profile.jsx
=> refector api and some chore

client/src/components/Header.jsx, client/src/pages/Profile.jsx
Tri
Theem popup
Header Profile
=> [Header][Profile] add popup

client/src/components/Header.jsx, client/src/pages/Products.jsx
TRipu
Nodata cho products
products
=> [Products] No data

client/src/components/ProductCard.jsx, client/src/utils/index.js
=> fix button and something else

client/src/components/Header.jsx, client/src/components/Loading.jsx
=> [Page] change z index header and loading

server/package.json, server/server.js, server/vercel.json
=> Deploy <(")

server/package.json
=> Change npm run build cli

server/.gitignore, server/data/products.js, server/data/users.js, server/pnpm-lock.yaml
=> Deploy with yaml

client/src/pages/Profile.jsx
=> [Profile] Fix loading
